
#delimit ;
lab def codprl
1  "Riz local gros grain  "
2  "Riz local long grain  "
3  "Riz importé populaire (dénicachia)  "
4  "Riz importé de luxe long grain  "
5  "Maïs en épi  "
6  "Maïs séché en grain (exclu maïs pop corn)  "
7  "Mil  "
8  "Sorgho  "
10  "Fonio  "
11  "Autres céréales en grain (à préciser) inclus maïs pop corn  "
12  "Farine de maïs  "
13  "Semoule de mais  "
14  "Farine de mil  "
15  "Semoule de mil  "
16  "Farine de blé local ou importé  "
17  "Couscous de blé  "
18  "Autres farines de céréales  "
19  "Autres semoules de céréales  "
20  "Pâtes alimentaires  "
21  "Pain moderne  "
22  "Pain traditionnel  "
23  "Croissants  "
24  "Biscuits  "
25  "Gâteaux  "
26  "Beignets, galettes  "
27  "Viande de bœuf  "
28  "Viande de chameau  "
29  "Viande de mouton  "
30  "Viande de chèvre  "
31  "Autres abats (foie, rognon, tête, patte, cou, gorge, os, testicule, queue, peau, etc.)  "
32  "Viande de porc  "
33  "Poulet sur pied  "
34  "Viande de poulet  "
35  "Viande d'autres volailles domestiques (pintade, canard, dindon; caille, pigeon…)  "
36  "Charcuterie (jambon, saucisson), conserves de viandes  "
37  "Viande séchée (boeuf, mouton, chameau, etc.)  "
38  "Gibiers (viande de brousse)  "
39  "Autres viandes n.d.a. ( à préciser lapin, grenouille, etc)  "
40  "Poisson frais Appolo  "
41  "Carpe blanche  "
42  "Poisson frais Carpe rouge  "
43  "Poisson frais Capitaine  "
44  "Poisson fumé Hareng (Mangni)  "
45  "Poisson fumé Maquereau  "
46  "Sardinelles fumées  "
47  "Crabes  "
48  "Crevettes fraiches  "
49  "Crevettes séchées  "
50  "Autres fruits de mer (écrevisse…)  "
51  "Conserves de poisson (sardine, thon…)  "
51  "Conserves de poisson  "
52  "Lait frais de vache  "
53  "Lait caillé, yaourt, dèguê  "
54  "Lait concentré sucré  "
55  "Lait concentré non-sucré  "
56  "Lait en poudre  "
57  "Fromage  "
58  "Lait et farines pour bébé  "
59  "Autres produits laitiers (crème fraiche, creme glâcée...)  "
60  "Œufs  "
61  "Beurre et Margarine  "
62  "Beurre de karité  "
63  "Huile de palme rouge  "
64  "Huile d'arachide raffinée  "
67  "Huile de coton  "
68  "Huile de palme raffinée  "
69  "Noix de palme( graine de palme)  "
70  "Autres huiles n.d.a. (maïs, huile palmiste, etc.)  "
71  "Mangue  "
72  "Ananas  "
73  "Orange  "
74  "Citron  "
75  "Autres agrumes (mandarine, pamplemousse, etc.)  "
76  "Banane douce  "
77  "Avocat  "
78  "Pastèque  "
79  "Melon  "
80  "Dattes  "
81  "Noix de coco  "
82  "Canne à sucre  "
83  "Pommes  "
84  "Papaye  "
85  "Fruit de baobab  "
86  "Néré  "
87  "Autres fruits (tamarin noir, liane sauvage, raisin, fraise, etc.)  "
88  "Salade (laitue)  "
89  "Chou  "
90  "Carotte  "
91  "Haricot vert  "
92  "Concombre  "
93  "Aubergine  "
94  "Courge/Courgette  "
95  "Poivron frais  "
96  "Tomate fraîche  "
97  "Tomate séchée  "
98  "Gombo frais  "
99  "Gombo sec/ séché/ pilé/poudre (djoumgbélé)  "
100  "Oignon frais  "
101  "Ail  "
102  "Feuilles d'oseille (dah)  "
103  "Feuilles de patate  "
104  "Epinards  "
105  "Kplala  "
106  "Autres feuilles (manioc, taro, baobab, haricot)  "
107  "Autre légumes frais n.d.a. (aubergine violette, navet etc)  "
108  "Concentré de tomate  "
109  "Petits pois  "
110  "Petit pois secs  "
111  "Autres légumes secs n.d.a. (soja, pistache etc)  "
112  "Niébé/Haricots secs  "
113  "Arachides fraîches en coques  "
114  "Arachides séchées en coques  "
115  "Arachides décortiquées  "
116  "Arachides pilées/ concassé  "
117  "Arachide grillée  "
118  "Pâte d'arachide  "
119  "Fromage à base de soja  "
120  "Sésame  "
121  "Noix de cajou  "
122  "Noix de karité  "
123  "Manioc  "
124  "Igname  "
125  "Banane plantain  "
126  "Pomme de terre  "
127  "Taro, macabo  "
128  "Patate douce  "
129  "Autres tubercules n.d.a  "
130  "Farines de manioc  "
131  "Gari, tapioca  "
132  "Attiéke/Atoukpou  "
133  "Fruit de Kapokier/ fromager  "
134  "Sucre poudre  "
135  "Sucre en morceaux  "
136  "Miel  "
137  "Chocolat à croquer, pâte à tartiner  "
138  "Caramel, bonbons, confiseries, etc  "
139  "Sel  "
140  "Piment séché/ poudre  "
141  "Piment frais  "
142  "Gingembre frais  "
143  "Gingembre moulu  "
144  "Cube alimentaire (Maggi, Jumbo, )  "
145  "Arôme (Maggi, aromate,adja, etc.)  "
146  "Soumbala (moutarde africaine)  "
147  "Mayonnaise  "
149  "Autres vinaigres  "
150  "Moutarde  "
151  "Poivre  "
152  "Autres condiments (akpi etc)  "
153  "Noix de cola  "
154  "Autres produits alimentaires (champignon …)  "
155  "Café en poudre (moulu)  "
156  "Café soluble (instantané)  "
157  "Thé (instantané)  "
158  "Chocolat en poudre  "
159  "Autres tisanes et infusions n.d.a. (quinquelibat, citronelle, etc.)  "
160  "Jus de fruits traditionnel (orange, bissap, gingembre, jus de cajou,etc.)  "
161  "Eau minérale/ filtrée  "
162  "Boissons gazeuses (coca, etc.)  "
163  "Jus en poudre  "
164  "Bières et vins traditionnels (Tchapalo, vin de palme, vin de raphia, vin de cajou, etc.)  "
165  "Bières industrielles (Bock, Guinness, Ivoire, Dopel, Chill, Heineken, Desperado etc)  "
166  "Riz importé brisure  "
167  "Céréales de petit déjeuner&nbsp;(quaker,corn flakes, granola, Flocon d’avoine, galette de riz soufflé..)  "
168  "Autres produits de boulangerie (pain de mie, pain de son etc)  "
169  "Pain sucré  "
170  "Tripes (intestin et estomac)  "
171  "Autres volailles domestiques sur pied (pintade, canard, caille, pigeon, dindon etc)  "
172  "Escargots  "
173  "Lait frais stérilisé sans sucre, demi-écremé/ écremé  "
174  "Pâte de manioc (placali)  "
175  "Poisson séché en condiment (adjovan)  "
176  "Feuille de Thé (Thé noir)  "
177  "Jus de fruits manufacturé (orange, mangue, ananas etc)  "

191"Petit déjeuner hors menage"
192"Déjeuner hors menage"
193"Dîner hors ménage"
194"Collation hors ménage"
195"Boissons chaudes hors ménage" 
196"Boisson non alcoolisée hors ménage"
197"Boisson alcoolisée hors ménage"


201"Cigarettes/Tabac"
202"Pétrole lampant"
203"Charbon de bois/minéral"
204"Bois de chauffe acheté"
205"Bois de chauffe ramassé"
206"Bougies"
207"Allumettes"
208"Carburant pour véhicule "
209"Carburant pour moto"
210"Transport urb. en taxi"
211"Transport urb. en bus"
212"Transport urb. en moto-taxi"
213"Transport urb. en train"
214"Transport urb. voie fluviale"
215"Transport urb. traction animale"
216"Journaux "
217"Frais moulure céréales"
301"Whisky/autres liqueurs"
302"Vins modernes"
303"Gaz domestique"
304"Carburant pour groupe elec."
305"Piles électriques"
306"Savon/détergents"
307"Insecticide, tortillon anti-moustique"
308"Salaire personnel de maison"
309"Frais blanchiment vêtements"
310"Frais ramassage ordures"
311"Lavage de véhicules"
312"Frais de parking"
313"Communication tél. cabine"
314"Billet lotterie/PMU"
315"Revues, journal ou magazine"
316"Frais coif., manucure, pédicure"
317"Savon toilette, shampoing"
318"Dentifrice"
319"Papier toilette"
320"Serv. hyg., couches jetables bébé"
321"Lait corporel, produits maquillage"
322"Masque jetable COVID-19"
323"Gel hydro-alcoolique"
324"Aut. prod. toil. (rasoir/coton)"
330"Loyer fictif autodeclaré"
331"Loyer maison"
332"Facture eau courante"
333"Eau aupres revendeur"
334"Facture electricite"
335"Facture telephone fixe"
336"Facture internet"
337"Facture abonnement cable"
338"Recharge telephone mobile"
401"Frais ent./rép. chaussures"
402"Ampoules électriques"
403"Lubrifiants"
404"Services rép./ent. trans. perso."
405"Transport inter-localité car"
406"Transport inter-localité traction animale"
407"Transport interlocalité par eau"
408"Timbre postaux, expédition mandat"
409"Frais envoi de fax"
410"Produits de jardinage"
411"Aliments/Entretien animaux de compagnie"
412"Droit entrée manifestations sportives"
413"Droit entrée cinéma/concert/théâtre, etc."
414"Autres services récréatifs (photo)"
415"Masque lavable contre la COVID-19"
416"Médicaments en pharmacie sans ordonnance"
417"Parfum"
418"Brosse à dents"
419"Contraceptifs"
420"Frais de photocopies de document"
421"Ticket de peage et assimilé"
501"Tissus habillement"
502"Vêtements femmes"
503"Sous-vêtements femme"
504"Vêtements enfants"
505"Vêtements hommes"
506"Sous-vêtements homme"
507"Frais confection vêtements homme"
508"Frais confection vêtements femme"
509"Frais de confection vêtements enfants"
510"Chaussures hommes"
511"Chaussures femmes"
512"Chaussures enfants"
521"Habits/Chaussures fêtes"
601"Matériel entretien/répar. du logement"
602"Main-oeuvre entretien/répar. logement" 
603"Mat. const. (ciment, briques, etc.)"
604"Aut. mat. const. (tôles, bois, élec., etc.)"
605"Main-oeuvre construction"
606"Frais puits/forage"
607"Frais acquisition terrain logement"
608"Frais études architecte"
609"Frais abonnement réseau eau"
610"Frais abonnement électricité"
611"Frais connexion eau"
612"Frais connexion électricité"
613"Meubles salon"
614"Lit/matelas et aut. meubles chambre"
615"Réparation de meubles"
616"Linge de maison "
617"Appareils électro-ménagers"
618"Plaque solaire "
619"Batterie plaque solaire/aut. équip. solaire  "
620"Réparation appareils électro-ménagers"
621"Vaisselle"
622"Ustensiles cuisine"
623"Autres ustensiles de ménage"
624"Outillage de maison"
625"Lampes (élect., tempêtes, torches)"
626"Achat voiture personnelle"
627"Achat moto personnelle"
628"Pièces détachées moyen loco."
629"Frais assurance moyen loco"
630"Vignette auto/moto"
631"Autres services relatifs aux véhicules personnels"
632"Location véhicule usage perso."
633"Transport inter-urb. en train"
634"Transport en avion"
635"Frais de déménagement"
636"Frais visa, taxes aéroport"
637"Achat téléphone portable"
638"Appareils musique/images"
639"Ordi./imprimante/tablette, etc."
640"Réparation appareils électroniques"
641"Petit mat. électronique usage perso."
642"Articles sport et détente"
643"Livre non scolaire, bande dessinée"
644"Papier rame/envelop./article dessin"
645"Frais pélérinage"
646"Formation professionnelle"
647"Frais cours particuliers pour adultes"
648"Services hébergement: hôtel, etc."
649"Montres, réveils"
650"Bijoux"
651"Autres effets personnels"
652"Frais assurance maison/moyen trans."
653"Taxes habitation/voiries"
654"Frais assurance vie"
655"Frais assurance maladie"
656"Frais évacuations sanitaires"
657"Frais légalisation doc. adm."
658"Aut. serv. (radio/tv, pompe funèbre, etc.)"
701"Frais insc./scol. préscolaire"
702"Cotisations préscolaire"
703"Livres/cahiers préscolaire"
704"Aut. matériel préscolaire"
705"Uniformes préscolaire" 
706"Frais cantine préscolaire"
707"Frais transport préscolaire"
708"Aut. (soutien, repet.) préscolaire"
709"Frais insc./scol. primaire"
710"Cotisations primaire"
711"Livres/cahiers primaire"
712"Aut. matériel primaire"
713"Uniformes primaire" 
714"Frais cantine primaire"
715"Frais transport primaire"
716"Aut. (soutien, repet.) primaire"
717"Frais insc./scol. secondaire 1"
718"Cotisations secondaire 1"
719"Livres/cahiers secondaire 1"
720"Aut. matériel secondaire 1"
721"Uniformes secondaire 1" 
722"Frais cantine secondaire 1"
723"Frais transport secondaire 1"
724"Aut. (soutien, repet.) secondaire 1"
725"Frais insc./scol. secondaire 2"
726"Cotisations secondaire 2"
727"Livres/cahiers secondaire 2"
728"Aut. matériel secondaire 2"
729"Uniformes secondaire 2" 
730"Frais cantine secondaire 2"
731"Frais transport secondaire 2"
732"Aut. (soutien, repet.) secondaire 2"
733"Frais insc./scol. post-secondaire"
734"Cotisations post-secondaire"
735"Livres/cahiers post-secondaire"
736"Aut. matériel post-secondaire"
737"Uniformes post-secondaire" 
738"Frais cantine post-secondaire"
739"Frais transport post-secondaire"
740"Aut. (soutien, repet.) post-secondaire"
741"Frais insc./scol. supérieur"
742"Cotisations supérieur"
743"Livres/cahiers supérieur"
744"Aut. matériel supérieur"
745"Uniformes supérieur" 
746"Frais cantine supérieur"
747"Frais transport supérieur"
748"Aut. (soutien, repet.) supérieur"
761"Consultation generaliste"
762"Consultation specialiste"
763"Consultation dentiste"
764"Consultation guerisseur"
765"Examens medicaux hors hosp."
766"Medic. modernes public hors hosp."
767"Medic. modernes privé hors hosp."
768"Medic. tradi. hors hosp."
769"Vaccinations"
770"Circonsition"
771"Bilan santé"
772"Test Covid"
773"Transport ambulance, etc."
774"Hospitalisation"
775"Frais accouchement"
776"Frais verres correcteurs/monture"
777"Béquil./chaises roul./prothèses, etc."
801"VU Salon (Fauteuils/table basse)"
802"VU Table manger (table/chaises)"
803"VU Lit "
804"VU Matelas simple"
805"VU Armoires et autres meubles"
806"VU Tapis"
807"VU Fer repasser electrique"
808"VU Fer repasser charbon"
809"VU Cuisiniere gaz/electrique"
810"VU Bonbonne de gaz"
811"VU Rechaud (plaque) gaz/electrique"
812"VU Four micro-onde/electrique"
813"VU Foyers ameliores"
814"VU Robot cuisine electrique"
815"VU Mixeur/Presse-fruits non elec."
816"VU Refrigerateur"
817"VU Congelateur"
818"VU Ventilateur sur pied"
819"VU Radio simple/Radiocassette"
820"VU Appareil TV"
821"VU Magnetoscope/CD/DVD"
822"VU Antenne parabolique/decodeur"
823"VU Lave-linge, seche linge"
824"VU Aspirateur"
825"VU Climatiseurs/splits"
826"VU Tondeuse gazon/jardinage"
827"VU Groupe electrogene"
828"VU Voiture personnelle"
829"VU Cyclomoteur/Vélomoteur"
830"VU Bicyclette"
831"VU Appareil photo"
832"VU Camescope"
833"VU Chaine Hi Fi"
834"VU Telephone fixe"
835"VU Telephone portable"
836"VU Tablette"
837"VU Ordinateur"
838"VU Imprimante/Fax"
839"VU Camera Video"
840"VU Pirogue/hors-bord plaisance"
841"VU Fusil de chasse"
842"VU Guitare"
843"VU Piano/appareil musique"
901"Alimentation fêtes"
902"Alimentation mariage/baptême/comm."
903"Alimentation funérailles/autres"
904"Boisson fêtes"
905"Boisson mariage/baptême/comm."
906"Boisson funérailles/autres"
908"Habits/chaussures mar./bapt./comm."
909"Habits/chaussures funér./autres"
910"Location salle/chaise fêtes"
911"Location salle/chaise mar./bapt./comm."
912"Location salle/chaise funér./autres"
;
#delimit cr
